# Generated by Django 4.0.4 on 2022-05-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(default='username', max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('account_number', models.CharField(max_length=10)),
                ('nationality', models.CharField(choices=[('Usa', 'Usa'), ('Nigerian', 'Nigerian'), ('British', 'British')], default='Usa', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
