# Generated by Django 4.0.4 on 2022-05-19 22:13

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
