# Generated by Django 4.0.4 on 2022-05-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
